### ISSUE TITLE
Modification données formulaire

### ISSUE THREAD

**Issue by lpojgc** [dthonon/Client_API_VN#282]
Je poursuis notre échange de mails ici pour garder la trace...

Ci-dessous mon message initial, complété avec les nouveaux essais suite à ta réponse :

_J'ai besoin de mettre à jour une série de données sur Faune Drôme.

J'ai réussi à en mettre à jour qq 10aines sans aucun problème mais là ça coince avec le message d'erreur ci-dessous. Le fichier correspondant se trouve en PJ, j'ai supprimé les lignes qui étaient passées sans problème._

``` sh
lpoaura@diomedea-bdd:~$ update_vn --verbose evn_aura.yaml to_update/onyx_all.csv
...
2022-09-02 15:55:58,738 - DEBUG - update_vn.update - ['site', 'id_universal', 'path', 'operation', 'value']
2022-09-02 15:55:58,738 - DEBUG - update_vn.update - ['vn26', '1095782', "$['data']['sightings'][0]['observers'][0]['project']", 'replace', '116']
2022-09-02 15:55:58,738 - INFO - update_vn.update - Site vn26 : mise à jour de l'observation 1095782, opération replace
Traceback (most recent call last):
  File "/home/lpoaura/.local/bin/update_vn", line 8, in <module>
    sys.exit(run())
  File "/home/lpoaura/.local/lib/python3.9/site-packages/update/update_vn.py", line 251, in run
    main(sys.argv[1:])
  File "/home/lpoaura/.local/lib/python3.9/site-packages/update/update_vn.py", line 243, in main
    update(cfg_ctrl, args.input)
  File "/home/lpoaura/.local/lib/python3.9/site-packages/update/update_vn.py", line 131, in update
    sighting["data"]["sightings"][0]["observers"][0],
IndexError: list index out of range
```

_Nous utilisons la version 2.7.1 du client._

J'ai également essayé avec les syntaxes
`$['data']['forms'][0]['sightings'][0]['observers'][0]['project']`
et 
`$['data']['forms'][1]['sightings'][0]['observers'][0]['project']`
en vain.
Le problème était déjà mentionné dans un ticket précédent et était réglé visiblement https://github.com/dthonon/Client_API_VN/issues/141#issuecomment-1119083203 (ou alors la cause est différente mais je ne vois pas d'où ça vient).

Est-ce que tu vois quelque chose que je rate ?

Merci !!

**Comment by dthonon** [comment]
Je pense avoir compris. J'avais oublié le ticket #141, qui corrige effectivement le problème. Il a été livré en version 2.8.0. Il faudrait que tu utilises une version plus récente que 2.7.1 pour en bénéficier. Et il ne faut pas ajouter de ['forms'][0], car ce ticket gère ces différences de format en interne.

**Comment by lpojgc** [comment]
je clôture, on avait un pb de version de notre client (utilisation d'une version + ancienne car utilisation des sites locaux)
